resources:
  repositories:
  - repository: mirepoix
    type: github
    name: xamarin/mirepoix
    ref: refs/heads/master
    endpoint: GitHub-XamarinInteractive

trigger:
- master

pr:
- master

jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - template: .vsts-ci-steps.yml

- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: .vsts-ci-steps.yml

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: .vsts-ci-steps.yml

  - script: |
      dotnet msbuild /noautoresponse /t:Pack /p:BuildProjectReferences=false /p:NoBuild=true /v:m /bl:_artifacts/pack.binlog mirepoix.proj
    displayName: Pack Libraries

  - task: PublishBuildArtifacts@1
    inputs:
      ArtifactName: Artifacts
      PathtoPublish: _artifacts
    displayName: Publish Artifacts
